name: Update stats (main)

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync-parallel-step-1:
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: 1
    secrets: inherit

  sync-parallel-step-2:
    needs: sync-parallel-step-1
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: 2
      is_prev_step_a: '1'
    secrets: inherit

  sync-parallel-step-3:
    needs: sync-parallel-step-2
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: 3
    secrets: inherit

  sync-parallel-step-4:
    needs: sync-parallel-step-3
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: 4
      is_prev_step_a: '3'
    secrets: inherit

  sync-parallel-step-5:
    needs: [sync-parallel-step-2, sync-parallel-step-4]
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: 5
      is_prev_step_a: '2'
      is_prev_step_b: '4'
      is_local_commit: 'true'
    secrets: inherit
